### ISSUE TITLE
Patches for `ignorefile` not applied in defined order

### ISSUE THREAD

**Issue by unstubbable** [clebert/onecfg-rust#4]
Given the following `onecfg.json`:

```json
{
  "extends": [
    "https://raw.githubusercontent.com/clebert/onecfg-lib/main/lib/onecfg-git.json"
  ],
  "patches": {
    ".gitignore": [
      {"value": ["# A grouping comment", "a-folder", "!a-folder/a-file"]}
    ]
  }
}
```

Expected `.gitignore` file:

```
# A grouping comment
a-folder
!a-folder/a-file
```

Actual `.gitignore` file:

```
!a-folder/a-file
# A grouping comment
a-folder
```

**Comment by clebert** [comment]
Currently ignore files are sorted alphabetically for aesthetic reasons. This decision is probably wrong since the order can indeed have an impact. I quote the Git documentation on this:

> An optional prefix "!" which negates the pattern; any matching file excluded by a previous pattern will become included again.
